### PR TITLE
Update map data

### PR DESCRIPTION
**Pull request by CarbonAlabel**
Closes https://github.com/esi/esi-issues/issues/1285

### CODE REVIEW

**Review by Blacksmoke16 — DISMISSED** [review]

**Comment by Blacksmoke16** [comment]
@mateuszkrasucki This is good to go I think. Anything special need to be done to get it released other than creating a new GH release?

**Review by Blacksmoke16 — APPROVED** [review]

**Comment by korashun** [comment]
Some news concerning the merge/release of the bugfix? Correct routes would be highly apriciated.

**Comment by Dusty-Meg** [comment]
@mateuszkrasucki @gitAskur could we get this merged in?
Repo is kind of useless with how out of date the map data is now

**Comment by gitAskur** [comment]
This is a tremendously broken process!

**Comment by Gh0stReaper123** [comment]
2 years for a map update. Wow.

**Comment by CarbonAlabel** [comment]
> This is a tremendously broken process!

Not like we need further evidence of this, but I had a hunch, ran the update script again, and it turns out the latest commit in this PR doesn't even contain the latest data; a couple of new changes have been made since then.

**Pull request merged**
